### ISSUE TITLE
数据集制作，使用的问题

### ISSUE THREAD

**Issue by 13281306705** [livin2/PoseBased-ActionRecognition#2]
博主，您好，请问您可以告诉我，您是怎么制作，使用数据集吗，或者您可以提供一下您使用的数据集吗，我是一名学生，这几天特别焦虑直到看到您写的代码。我的邮箱是1317594600@qq.com，如果博主回复我，那就万分感谢了，谢谢博主

**Comment by 13281306705** [comment]
特别想学习一下，所以打扰博主了

**Comment by nahpixz** [comment]
姿态估计MSCOCO/MPII 见交大AlphaPose 项目
动作分类 HDMB51
